{% set name = "CoolProp" %}

# WARNING external resources may need update as well
{% set version = "6.7.0" %}
{% set sha256 = "7a014b74d95da8b00bc30e61546398fd6d5c7f65066a092fb15efb7b17d3b76c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/CoolProp/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: {{ sha256 }}
    patches:
      - setup.patch
      - eigen.patch
  # External dependencies
  # See https://github.com/CoolProp/CoolProp/tree/master/externals
  - url: https://github.com/CoolProp/IF97/archive/a103894253ccd5144050eaeb8f7276379b9e5d9d.tar.gz
    sha256: 82af3e67fefaaa648d0a1550aac2f3c9dce054e7e0f28b3164ce6a30001f7938
    folder: externals/IF97
  - url: https://github.com/CoolProp/REFPROP-headers/archive/b4faab1b73911c32c4b69c526c7e92f74edb67de.zip
    sha256: a98351b3618e0f9f5dc95da219feaf55d029b5f5b961fdfb8262ad3e7e6e89a7
    folder: externals/REFPROP-headers
  - url: https://github.com/fmtlib/fmt/archive/10.0.0.tar.gz
    sha256: ede1b6b42188163a3f2e0f25ad5c0637eca564bd8df74d02e31a311dd6b37ad8
    folder: externals/fmtlib
  - url: https://github.com/msgpack/msgpack-c/archive/cpp-7.0.0.tar.gz
    sha256: 070881ebea9208cf7e731fd5a46a11404025b2f260ab9527e32dfcb7c689fbfc
    folder: externals/msgpack-c
  - url: https://github.com/Tencent/rapidjson/archive/73063f5002612c6bf64fe24f851cd5cc0d83eef9.zip
    sha256: 013edcc40afd7a550899e443ac70bc16b6a36867393be50f1def35674e2be08c
    folder: externals/rapidjson

build:
  number: 2
  # pypy is not passing and we don't want to support it
  skip: true  # [python_impl == 'pypy']

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make   # [not win]
    - ninja  # [win]
  host:
    - python
    - cython
    - setuptools
    - pip
    - catch2
    - eigen
  run:
    - python
    - numpy
    - matplotlib-base

test:
  imports:
    - CoolProp
    - CoolProp.tests
    - CoolProp.Plots  # [not py2k or not linux]
    - CoolProp.GUI

about:
  home: https://github.com/CoolProp/CoolProp
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Open-source thermodynamic and transport properties database

  description: |
    Open-source thermodynamic and transport properties database
  doc_url: http://www.coolprop.org/
  dev_url: https://github.com/CoolProp/CoolProp

extra:
  recipe-maintainers:
    - danilomendesdias
    - fcollonval
