{% set name = "CoolProp" %}

# WARNING external resources may need update as well
{% set version = "7.0.0" %}
{% set sha256 = "181209dd9144f2b325115822fdb60e9aba91948b27e36a774b17607023a04003" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/CoolProp/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: {{ sha256 }}
    patches:
      - setup.patch
      - rapidjson.patch
  # External dependencies
  # See https://github.com/CoolProp/CoolProp/tree/master/externals
  - url: https://github.com/CoolProp/IF97/archive/3ddd548f87f55db921a490ae4facb36162497009.tar.gz
    sha256: ba2ac3ffe69fc0045424eddc492b1a18041e45fefdcfaf6ea1f6ae9abc72cba8
    folder: externals/IF97
  - url: https://github.com/CoolProp/REFPROP-headers/archive/b4faab1b73911c32c4b69c526c7e92f74edb67de.zip
    sha256: a98351b3618e0f9f5dc95da219feaf55d029b5f5b961fdfb8262ad3e7e6e89a7
    folder: externals/REFPROP-headers

build:
  number: 0
  # pypy is not passing and we don't want to support it
  skip: true  # [python_impl == 'pypy']

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make   # [not win]
    - ninja  # [win]
  host:
    - python
    - cython
    - setuptools
    - pip
    - catch2
    - eigen
    - fmt =10.2.1
    - msgpack-c
    - msgpack-cxx
    - rapidjson
  run:
    - python
    - numpy
    - matplotlib-base

test:
  imports:
    - CoolProp
    - CoolProp.tests
    - CoolProp.Plots  # [not py2k or not linux]
    - CoolProp.GUI

about:
  home: https://github.com/CoolProp/CoolProp
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Open-source thermodynamic and transport properties database

  description: |
    Open-source thermodynamic and transport properties database
  doc_url: http://www.coolprop.org/
  dev_url: https://github.com/CoolProp/CoolProp

extra:
  recipe-maintainers:
    - danilomendesdias
    - fcollonval
    - jan-janssen
