{% set name = "CoolProp" %}

{% set version = "6.2.1" %}
{% set sha256 = "e94a65e5bbf150e4010816160f66b2095dc70b598461bb1fa664bb5791922c93" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/CoolProp/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: {{ sha256 }}
    patches:
      - FindPythonAnaconda.patch
      - CMakeLists.patch
  - url: https://github.com/catchorg/Catch2/archive/v1.12.2.tar.gz
    sha256: 27bf01d20692e534a8963f96c6ca797df2b4ba6551db0379510c376558d75e3c
    folder: externals/Catch
  - url: https://github.com/eigenteam/eigen-git-mirror/archive/3.3.5.tar.gz
    # sha256:
    folder: externals/Eigen
  - url: https://github.com/msgpack/msgpack-c/archive/cpp-3.0.1.tar.gz
    # sha256:
    folder: externals/msgpack-c
  - url: https://github.com/fmtlib/fmt/archive/4.1.0.tar.gz
    # sha256:
    folder: externals/fmtlib

build:
  number: 1002

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - cython
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - matplotlib-base

test:
  imports:
    - CoolProp
    - CoolProp.tests
    - CoolProp.Plots
    - CoolProp.GUI

about:
  home: https://github.com/CoolProp/CoolProp
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Open-source thermodynamic and transport properties database'

  description: |
    Open-source thermodynamic and transport properties database
  doc_url: http://www.coolprop.org/
  dev_url: https://github.com/CoolProp/CoolProp

extra:
  recipe-maintainers:
    - danilomendesdias
