{% set name = "CoolProp" %}

{% set version = "6.2.1" %}
{% set sha256 = "e94a65e5bbf150e4010816160f66b2095dc70b598461bb1fa664bb5791922c93" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/CoolProp/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1002
  script: "cd wrappers/Python && python setup.py install cmake=default,64"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - cython
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - matplotlib-base

test:
  imports:
    - CoolProp
    - CoolProp.tests
    - CoolProp.Plots
    - CoolProp.GUI

about:
  home: https://github.com/CoolProp/CoolProp
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Open-source thermodynamic and transport properties database'

  description: |
    Open-source thermodynamic and transport properties database
  doc_url: http://www.coolprop.org/
  dev_url: https://github.com/CoolProp/CoolProp

extra:
  recipe-maintainers:
    - danilomendesdias
