travis:
  secure:
    BINSTAR_TOKEN: iXQo8VwhyGPf2vbHT4x2l934CIkWvn+gw6/Uuivt71+lDOFfMhnT49M9a3Qp6bQEOkWccPjCQDpBj/c9v5A1bPh1My9LlZHL5ZrAkUdmoJAvplo0cY8VHCz+WEmTpGCs8JtdxhuMkuab0Z3pwH2GtT/zJEjzvmaCJ6yBHjeDiQODNqGUduESRvZ98ce9mTOtSV/lRtdbwE3hEUNOHLn9elOb+XcBytifHcoNXWuEupQpidS7WtHcLX4bBOhu66A3DkNBClhzVYsGhsBkh5mo76lPGS3ouiURvP/mgI5qCt5GQHtX4PiMr6s0aFrd47INm2+Z4+MccNP8b7NMJo8KR0Psn36yHZaaZro+TtrURnYYBSSB2OateO4MuFHgiANeuTSriSRi/HEz7K8C4dbb1VNK8XoF7Env1Tg0XvPBlSCGoGleDimWkR0vBqwSqUhGMfJ3RJUJeZ3KBANSDcDZ4qo6BC12lLw9iX7h0Vfu2KhIzxQQr7phBvlg9F44PY1U2Pbp0BjzK/8BLm45HU9k0R5bECZIyst8hdufJwJqsGHAmuoq/t4Z+kJbDhxfcKoOnbTrqVyLu0GYvQr1bnDw0vnXPjdZ61pSAvVtA6DHICGJzwQ8dthtXpldr98O+OsMab3svK/QkONnFstOLHKq1QZasE3lvKCkmIJWGrVDEY8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
